require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'app/assets/**/*'
    - 'tmp/**/*'
    - 'uploads/**/*'
    - 'public/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'coverage/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'mecab-master/**/*' #circleciでmecabをrootに入れているため
  DisplayCopNames: true
  TargetRubyVersion: 2.6

Rails:
  Enabled: true
Rails/FindEach:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Naming/AccessorMethodName:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: true

# redirect_to xxx and return のイディオムを維持したい
Style/AndOr:
  EnforcedStyle: conditionals


Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Style/Attr:
  Enabled: false

Style/BeginBlock:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: true

Style/BlockComments:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  Enabled: true

Style/CharacterLiteral:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: true

Style/CommentAnnotation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Layout/ElseAlignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/EndBlock:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/EvenOdd:
  Enabled: true

Naming/FileName:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Lint/FlipFlop:
  Enabled: false

Style/For:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GlobalVars:
  Enabled: false
  #OFF

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/IndentationWidth:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: special_inside_parentheses, consistent, align_braces

Layout/FirstHashElementIndentation:
  EnforcedStyle: special_inside_parentheses

Style/InfiniteLoop:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Naming/MethodName:
  Enabled: false
  #OFF

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: false

Style/Next:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    "%i": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
  # rubocopのバージョンでエラーになるので一旦off

Style/RedundantSelf:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/RescueModifier:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAfterMethodName:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: false

Layout/SpaceAfterSemicolon:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: space

Layout/SpaceBeforeComma:
  Enabled: true

Layout/SpaceBeforeComment:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MutableConstant:
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StructInheritance:
  Enabled: false

Style/SymbolProc:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrivialAccessors:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/RedundantCapitalW:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: true

Style/VariableInterpolation:
  Enabled: false

Naming/VariableName:
  Enabled: false
  #OFF

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true

Style/WordArray:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/RedundantStringCoercion:
  Enabled: true

Layout/EndAlignment:
  Enabled: false
  # AutoCorrect: true
  # AlignWith: start_of_line
  #OFF バグっているらしい

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Layout/LineLength:
  Max: 120
  AllowURI: true
  AllowHeredoc: true
  URISchemes:
    - http
    - https
  Exclude:
    - config/initializers/devise.rb
    - config/initializers/secret_token.rb
    - spec/support/factories/facebooks.rb
    - lib/jmty/blue_green_deploy.rb

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/Validation:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true

Style/CaseEquality:
  Enabled: false

#mongoid使っている間は必ずしも改善できない
# L556 で有効化している
# Performance/Detect:
#   Enabled: false

Performance/RedundantMatch:
  Enabled: true

#mongoid使っているのでむしろ使うべき
Rails/HasAndBelongsToMany:
  Enabled: false

# Mongoidをメインで使っているためwhere().exists?が正しい
Rails/WhereExists:
  Enabled: false

#module includeやrelationの関連で引っかかるため
Lint/NestedMethodDefinition:
  Enabled: false

Lint/Debugger:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: false

Lint/UnusedBlockArgument:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Style/ParallelAssignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Style/NestedParenthesizedCalls:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowInnerBackticks.
# SupportedStyles: backticks, percent_x, mixed
Style/CommandLiteral:
  EnforcedStyle: backticks

# Cop supports --auto-correct.
# Configuration parameters: EnforcedOctalStyle, SupportedOctalStyles.
# SupportedOctalStyles: zero_with_o, zero_only
Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

# Offense count: 111
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Enabled: false

# Offense count: 34
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AllowSafeAssignment.
# SupportedStyles: require_parentheses, require_no_parentheses
Style/TernaryParentheses:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false
# 継承などが考慮されていない為OFF

inherit_from: .rubocop_todo.yml

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging
