production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        connect_timeout: 15
        raise_not_found_error: false

development:
  clients:
    default:
      database: rails_attendance_development
      hosts:
        - localhost:27017
      options:
        connect_timeout: 15
        raise_not_found_error: false

test:
  clients:
    default:
      database: rails_attendance_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
